name: CI

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: PR Smoke (${{ matrix.os }} • ${{ matrix.browser }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        browser: [chromium]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Playwright cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/ms-playwright
            /home/runner/.cache/ms-playwright
          key: pw-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pw-${{ runner.os }}-

      - name: Install Playwright (Linux)
        if: runner.os == 'Linux'
        run: python -m playwright install --with-deps

      - name: Install Playwright (Windows)
        if: runner.os == 'Windows'
        run: python -m playwright install

      - name: Run smoke tests
        env:
          RUN_SUITE: smoke
          BROWSER: ${{ matrix.browser }}
        run: python tools/run_all.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}-${{ matrix.browser }}
          path: |
            artifacts/**
            playwright-report/**
            reports/**

  nightly:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Full run
        env:
          RUN_SUITE: full
        run: python tools/run_all.py

      - name: Upload nightly artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nightly-artifacts
          path: |
            artifacts/**
            playwright-report/**
            reports/**
